import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'
import { baseParse, NodeTypes } from '@vue/compiler-dom'
import { parse as parseVueSfc } from '@vue/compiler-sfc'
import { compileNovaCss, generateNovaCssModule, serializeStyleAsset } from '@/css/nova-css-compiler'
import { compileNovaSfc, compileTimelineTaskProfilesSource } from '@/sfc/nova-sfc-compiler'

export interface NovaGeneratedOutputOptions {
  enabled?: boolean
  dir?: string
}

export interface NovaVitePluginOptions {
  includeDiagnostics?: boolean
  generatedOutput?: NovaGeneratedOutputOptions
}

interface VirtualNovaModule {
  source: string
  filename: string
  ownerFile: string
  versionedId?: string
}

interface ParsedAttr {
  name: string
  value: string | true
}

interface VueNovaStyleTransform {
  source: string
  styles: Array<string>
  scopedStyles: Array<string>
  globalStyles: Array<string>
}

interface Replacement {
  start: number
  end: number
  value: string
}

interface InlineVueBinding {
  propName: string
  expression: string
}

interface NormalizedInlineTemplate {
  source: string
  bindings: Array<InlineVueBinding>
}

const NOVA_GEN_DEBUG_ENV = 'NOVA_GEN_DEBUG_ENABLED'
const DEFAULT_GENERATED_OUTPUT_DIR = '.nova-generated'
const GENERATED_OUTPUT_HEADER = '// Generated by @endge/nova-compiler. Do not edit.\n\n'
const NOVA_STYLE_LANGS = new Set(['novacss'])

/** Vite plugin для `.nova`, `.novacss` и Vue `NovaCanvas` inline DSL. */
export function novaVitePlugin(options: NovaVitePluginOptions = {}): Plugin {
  const generatedOutput = resolveGeneratedOutputOptions(options.generatedOutput)
  const virtualModules = new Map<string, VirtualNovaModule>()

  return {
    name: 'endge-nova-compiler',
    enforce: 'pre',

    /**
     * Нормализует и возвращает итоговое значение текущего класса.
     */
    resolveId(id) {
      if (virtualModules.has(stripViteQuery(id))) return id
      return null
    },

    /**
     * Загружает данные или ресурсы текущего класса.
     */
    load(id) {
      const virtualModule = virtualModules.get(stripViteQuery(id))
      if (!virtualModule) return null
      return compileNovaModule(virtualModule.source, virtualModule.filename, this, options, generatedOutput)
    },

    /**
     * Обрабатывает runtime-событие текущего класса.
     */
    handleHotUpdate(context) {
      const ownerFile = stripViteQuery(context.file)
      for (const [id, virtualModule] of virtualModules.entries()) {
        if (virtualModule.ownerFile !== ownerFile) continue

        const moduleIds = [id, virtualModule.versionedId].filter(Boolean) as Array<string>
        for (const moduleId of moduleIds) {
          const module = context.server.moduleGraph.getModuleById(moduleId)
          if (module) context.server.moduleGraph.invalidateModule(module)
        }
      }

      return undefined
    },

    /**
     * Преобразует значение в целевую модель текущего класса.
     */
    transform(source, id) {
      const cleanId = stripViteQuery(id)

      if (virtualModules.has(cleanId)) {
        return null
      }

      if (cleanId.endsWith('.novacss')) {
        const result = compileNovaCss(source, {
          filename: cleanId,
          resolveImport: (request, from) => resolveSourceImport(request, from, this),
        })
        const code = generateNovaCssModule(result, {
          sideEffect: !hasViteQuery(id, 'asset'),
        })
        emitDiagnostics(cleanId, result.diagnostics, options.includeDiagnostics ?? true)
        throwOnErrors(result.diagnostics)
        writeGeneratedOutput(generatedOutput, cleanId, code)
        return {
          code,
          map: null,
        }
      }

      if (cleanId.endsWith('.nova')) {
        return {
          code: compileNovaModule(source, cleanId, this, options, generatedOutput),
          map: null,
        }
      }

      if (cleanId.endsWith('.vue') && !isVueSubBlockRequest(id) && !id.includes('?raw')) {
        clearVueInlineVirtualModules(virtualModules, cleanId)
        const novaStyles = extractVueNovaStyles(source)
        let transformed = novaStyles.source
        let hasTransform = false

        const timelineProfiles = transformVueTimelineChartProfiles(
          transformed,
          cleanId,
          this,
          virtualModules,
          options.includeDiagnostics ?? true,
          novaStyles.scopedStyles,
        )
        if (timelineProfiles) {
          transformed = timelineProfiles
          hasTransform = true
        }

        const novaCanvas = transformVueNovaCanvasTemplates(transformed, cleanId, virtualModules, options.includeDiagnostics ?? true, novaStyles.scopedStyles)
        if (novaCanvas) {
          transformed = novaCanvas
          hasTransform = true
        }

        if (novaStyles.globalStyles.length > 0) {
          transformed = injectVueGlobalNovaStyles(
            transformed,
            cleanId,
            this,
            options.includeDiagnostics ?? true,
            novaStyles.globalStyles,
          )
          hasTransform = true
        }

        if (hasTransform) {
          writeGeneratedOutput(generatedOutput, `${cleanId}__nova_template_transform`, transformed)
          return {
            code: transformed,
            map: null,
          }
        }
      }

      return null
    },
  }
}

function compileNovaModule(
  source: string,
  id: string,
  context: { addWatchFile: (id: string) => void },
  options: NovaVitePluginOptions,
  generatedOutput: Required<NovaGeneratedOutputOptions>,
): string {
  const result = compileNovaSfc(source, {
    filename: id,
    resolveImport: (request, from) => resolveSourceImport(request, from, context),
  })
  emitDiagnostics(id, result.diagnostics, options.includeDiagnostics ?? true)
  throwOnErrors(result.diagnostics)
  writeGeneratedOutput(generatedOutput, id, result.code)
  return result.code
}

function transformVueNovaCanvasTemplates(
  source: string,
  id: string,
  virtualModules: Map<string, VirtualNovaModule>,
  _includeDiagnostics: boolean,
  novaStyleBlocks: Array<string> = [],
): string | null {
  if (!hasVueNovaCanvasSource(source)) return null

  const imports: Array<string> = []
  const replacements: Array<Replacement> = []
  let index = 0

  const sfc = parseVueSfc(source, { filename: id })
  const template = sfc.descriptor.template
  if (!template) return null

  const ast = baseParse(template.content)
  const templateOffset = template.loc.start.offset

  walkVueTemplateElements(ast, node => {
    if (node.tag !== 'NovaCanvas') return
    if (!Array.isArray(node.children)) return

    const novaSlot = node.children.find((child: any) => getNamedVueTemplateName(child) === 'nova')
    const defaultChildren = node.children.filter((child: any) => (
      !isNamedVueTemplate(child)
      && !isNovaTemplateMarker(child)
      && !isEmptyTextNode(child)
    ))
    const novaChildren = novaSlot
      ? novaSlot.children.filter((child: any) => !isEmptyTextNode(child))
      : defaultChildren
    if (novaChildren.length === 0) return

    const componentName = `__NovaTemplate${index}`
    const debugId = `${stripViteQuery(id)}__nova_template_${index}`
    const nodeSource = node.loc.source
    const openingEndInNode = nodeSource.indexOf('>') + 1
    const openingSource = openingEndInNode > 0 ? nodeSource.slice(0, openingEndInNode) : nodeSource
    const rawDefaultSource = novaChildren.map((child: any) => child.loc.source).join('\n').trim()
    const normalizedTemplate = normalizeInlineVueTemplateBindings(rawDefaultSource)
    const defaultSource = normalizedTemplate.source
    const importSource = `virtual:nova-template:${stripViteQuery(id)}:${index}.nova`
    const inlineSource = createInlineNovaCanvasTemplateSource(defaultSource, novaStyleBlocks)
    const virtualVersionSource = inlineSource
    virtualModules.set(importSource, {
      filename: `${stripViteQuery(id)}__nova_template_${index}.nova`,
      source: inlineSource,
      ownerFile: stripViteQuery(id),
    })

    const importModuleSource = withVirtualVersion(importSource, virtualVersionSource)
    virtualModules.get(importSource)!.versionedId = importModuleSource
    imports.push(`import ${componentName} from ${JSON.stringify(importModuleSource)};`)

    const refNames = collectNovaTemplateRefs(defaultSource)
    const refsAttr = refNames.length > 0 ? ` :nova-refs="{ ${refNames.join(', ')} }"` : ''
    const bindingAttrs = normalizedTemplate.bindings
      .map(binding => ` :${toKebabCase(binding.propName)}="${binding.expression}"`)
      .join('')
    const marker = `<template #nova><nova-template :component="${componentName}" source="${escapeAttr(importModuleSource)}" debug-id="${escapeAttr(debugId)}"${refsAttr}${bindingAttrs} /></template>`
    const namedSlots = node.children
      .filter((child: any) => isNamedVueTemplate(child) && getNamedVueTemplateName(child) !== 'nova')
      .map((child: any) => child.loc.source)
      .join('\n')
    const replacement = `${openingSource}\n${marker}${namedSlots ? `\n${namedSlots}` : ''}\n</${node.tag}>`

    replacements.push({
      start: templateOffset + node.loc.start.offset,
      end: templateOffset + node.loc.end.offset,
      value: replacement,
    })
    index += 1
  })

  if (replacements.length === 0) return null
  return injectVueScriptSetupImports(applyReplacements(source, replacements), imports.join('\n'))
}

function transformVueTimelineChartProfiles(
  source: string,
  id: string,
  context: { addWatchFile: (id: string) => void },
  virtualModules: Map<string, VirtualNovaModule>,
  includeDiagnostics: boolean,
  novaStyleBlocks: Array<string> = [],
): string | null {
  if (!hasVueTimelineChartProfileSource(source)) return null

  const declarations: Array<string> = []
  const imports: Array<string> = []
  const replacements: Array<Replacement> = []
  let index = 0
  let timelineStyleAssetName = ''

  const sfc = parseVueSfc(source, { filename: id })
  const template = sfc.descriptor.template
  if (!template) return null

  const ast = baseParse(template.content)
  const templateOffset = template.loc.start.offset

  walkVueTemplateElements(ast, node => {
    if (node.tag !== 'TimelineChart') return
    const children = Array.isArray(node.children) ? node.children : []

    const profileChildren = children.filter((child: any) => isTimelineTaskProfileVueNode(child))
    const rootChildren = children.filter((child: any) => (
      !isTimelineTaskProfileVueNode(child)
      && !isEmptyTextNode(child)
    ))
    const shouldInjectStyleSheet = novaStyleBlocks.length > 0 && !hasVueStyleSheetProp(node)
    if (profileChildren.length === 0 && rootChildren.length === 0 && !shouldInjectStyleSheet) return

    let profilesProp = ''
    if (profileChildren.length > 0) {
      const profilesSource = profileChildren.map((child: any) => child.loc.source).join('\n')
      const result = compileTimelineTaskProfilesSource(profilesSource, {
        filename: id,
        resolveImport: (request, from) => resolveSourceImport(request, from, context),
      })
      emitDiagnostics(id, result.diagnostics, includeDiagnostics)
      throwOnErrors(result.diagnostics)

      const constName = `__timelineTaskProfiles${index}`
      declarations.push(`const ${constName} = ${result.code};`)
      profilesProp = ` :compiled-task-profiles="${constName}"`
    }

    let rootChildrenProp = ''
    if (rootChildren.length > 0) {
      const componentName = `__TimelineRootChildren${index}`
      const rawSource = rootChildren.map((child: any) => child.loc.source).join('\n').trim()
      const normalizedTemplate = normalizeInlineVueTemplateBindings(rawSource)
      const inlineSource = createInlineNovaTemplateSource(normalizedTemplate.source, novaStyleBlocks)
      const importSource = `virtual:nova-template:${stripViteQuery(id)}:timeline-root-${index}.nova`
      virtualModules.set(importSource, {
        filename: `${stripViteQuery(id)}__timeline_root_children_${index}.nova`,
        source: inlineSource,
        ownerFile: stripViteQuery(id),
      })
      const importModuleSource = withVirtualVersion(importSource, inlineSource)
      virtualModules.get(importSource)!.versionedId = importModuleSource
      imports.push(`import ${componentName} from ${JSON.stringify(importModuleSource)};`)
      const props = normalizedTemplate.bindings.length > 0
        ? `props:{${normalizedTemplate.bindings.map(binding => `${binding.propName}:${binding.expression}`).join(',')}}`
        : ''
      rootChildrenProp = ` :compiled-root-children="[{ type: ${componentName}${props ? `, ${props}` : ''} }]"`
    }

    let styleSheetProp = ''
    if (shouldInjectStyleSheet) {
      if (!timelineStyleAssetName) {
        timelineStyleAssetName = '__timelineChartNovaStyleSheet'
        declarations.push(`const ${timelineStyleAssetName} = ${compileVueNovaStyleBlocksAssetCode(
          novaStyleBlocks,
          id,
          context,
          includeDiagnostics,
        )};`)
      }
      styleSheetProp = ` :style-sheet="${timelineStyleAssetName}"`
    }

    const nodeSource = node.loc.source
    const openingEndInNode = nodeSource.indexOf('>') + 1
    const openingSource = openingEndInNode > 0 ? nodeSource.slice(0, openingEndInNode) : nodeSource
    const injectedProps = `${profilesProp}${rootChildrenProp}${styleSheetProp}`
    const openingWithProfiles = openingSource.trimEnd().endsWith('/>')
      ? openingSource.replace(/\/>$/, `${injectedProps}>`)
      : openingSource.replace(/>$/, `${injectedProps}>`)
    const replacement = `${openingWithProfiles}\n</${node.tag}>`

    replacements.push({
      start: templateOffset + node.loc.start.offset,
      end: templateOffset + node.loc.end.offset,
      value: replacement,
    })
    index += 1
  })

  if (replacements.length === 0) return null
  return injectVueScriptSetupImports(applyReplacements(source, replacements), [...imports, ...declarations].join('\n'))
}

function compileVueNovaStyleBlocksAssetCode(
  blocks: Array<string>,
  id: string,
  context: { addWatchFile: (id: string) => void },
  includeDiagnostics: boolean,
): string {
  const source = blocks.map(block => readVueNovaStyleBlockSource(block, id, context)).join('\n')
  const result = compileNovaCss(source, {
    filename: id,
    resolveImport: (request, from) => resolveSourceImport(request, from, context),
  })
  emitDiagnostics(id, result.diagnostics, includeDiagnostics)
  throwOnErrors(result.diagnostics)
  return serializeStyleAsset(result)
}

function injectVueGlobalNovaStyles(
  source: string,
  id: string,
  context: { addWatchFile: (id: string) => void },
  includeDiagnostics: boolean,
  novaStyleBlocks: Array<string>,
): string {
  const assetName = `__novaGlobalStyleSheet${hashString(`${id}:${novaStyleBlocks.join('\n')}`)}`
  const assetCode = compileVueNovaStyleBlocksAssetCode(novaStyleBlocks, id, context, includeDiagnostics)
  return injectVueScriptSetupImports(source, [
    `import { Nova as __NovaRuntime } from '@endge/nova';`,
    `const ${assetName} = ${assetCode};`,
    `__NovaRuntime.import(${assetName});`,
  ].join('\n'))
}

function readVueNovaStyleBlockSource(
  block: string,
  id: string,
  context: { addWatchFile: (id: string) => void },
): string {
  const match = block.match(/^<style\b([^>]*)>([\s\S]*?)<\/style>$/i)
  if (!match) return block

  const attrs = parseAttrs(match[1] ?? '')
  const src = readParsedAttr(attrs, 'src')
  if (!src) return match[2] ?? ''

  const imported = resolveSourceImport(src, id, context)
  if (!imported) return ''
  return typeof imported === 'string' ? imported : imported.source
}

function extractVueNovaStyles(source: string): VueNovaStyleTransform {
  const styles: Array<string> = []
  const scopedStyles: Array<string> = []
  const globalStyles: Array<string> = []
  const transformed = source.replace(/<style\b([^>]*)>([\s\S]*?)<\/style>/gi, (raw: string, attrsSource: string) => {
    const attrs = parseAttrs(attrsSource)
    const lang = readParsedAttr(attrs, 'lang')?.toLowerCase()
    if (!lang || !NOVA_STYLE_LANGS.has(lang)) return raw

    styles.push(raw)
    if (attrs.some(attr => attr.name === 'scoped')) {
      scopedStyles.push(raw)
    } else {
      globalStyles.push(raw)
    }
    return ''
  })

  return {
    source: transformed,
    styles,
    scopedStyles,
    globalStyles,
  }
}

function createInlineNovaTemplateSource(templateSource: string, novaStyleBlocks: Array<string>): string {
  const blocks = [`<template>\n${templateSource}\n</template>`]
  if (novaStyleBlocks.length) blocks.push(...novaStyleBlocks)
  return blocks.join('\n\n')
}

function createInlineNovaCanvasTemplateSource(templateSource: string, novaStyleBlocks: Array<string>): string {
  return createInlineNovaTemplateSource(resolveNovaCanvasRootSource(templateSource), novaStyleBlocks)
}

function resolveNovaCanvasRootSource(templateSource: string): string {
  if (isSingleTopLevelNovaRoot(templateSource)) return templateSource

  return `<Root
  :id="props.rootId ?? 'nova-canvas-root'"
  :width="props.width"
  :height="props.height"
  :padding="props.padding"
  :background="props.background"
  :border="props.border"
  :clip="props.clip"
  :class="props.rootClassName"
  :styleSheet="props.styleSheet ?? styleSheet"
>
${templateSource}
</Root>`
}

function isSingleTopLevelNovaRoot(templateSource: string): boolean {
  try {
    const ast = baseParse(`<template>${templateSource}</template>`)
    const root = ast.children.find((child: any) => child.type === NodeTypes.ELEMENT && child.tag === 'template') as any
    const children = root?.children?.filter((child: any) => !isEmptyTextNode(child)) ?? []
    return children.length === 1 && children[0]?.type === NodeTypes.ELEMENT && children[0].tag === 'Root'
  } catch {
    return false
  }
}

function walkVueTemplateElements(node: any, visit: (node: any) => void): void {
  if (node.type === NodeTypes.ELEMENT) visit(node)
  if (!Array.isArray(node.children)) return
  for (const child of node.children) walkVueTemplateElements(child, visit)
}

function hasVueNovaCanvasSource(source: string): boolean {
  return source.includes('<NovaCanvas')
}

function hasVueTimelineChartProfileSource(source: string): boolean {
  return source.includes('<TimelineChart')
}

function hasVueStyleSheetProp(node: any): boolean {
  for (const prop of node.props ?? []) {
    if (prop.type === NodeTypes.ATTRIBUTE && (prop.name === 'style-sheet' || prop.name === 'styleSheet')) return true
    if (prop.type !== NodeTypes.DIRECTIVE || prop.name !== 'bind') continue
    const arg = prop.arg?.content
    if (arg === 'style-sheet' || arg === 'styleSheet') return true
  }
  return false
}

function isTimelineTaskProfileVueNode(node: any): boolean {
  return node.type === NodeTypes.ELEMENT && node.tag === 'TimelineTaskProfile'
}

function isNamedVueTemplate(node: any): boolean {
  return node.type === NodeTypes.ELEMENT
    && node.tag === 'template'
    && node.props?.some((prop: any) => prop.type === NodeTypes.DIRECTIVE && prop.name === 'slot')
}

function getNamedVueTemplateName(node: any): string | null {
  if (!isNamedVueTemplate(node)) return null
  const slot = node.props.find((prop: any) => prop.type === NodeTypes.DIRECTIVE && prop.name === 'slot')
  return typeof slot?.arg?.content === 'string' ? slot.arg.content : 'default'
}

function isEmptyTextNode(node: any): boolean {
  return node.type === NodeTypes.TEXT && !node.content.trim()
}

function isNovaTemplateMarker(node: any): boolean {
  return node.type === NodeTypes.ELEMENT && node.tag === 'nova-template'
}

function collectNovaTemplateRefs(templateSource: string): Array<string> {
  const refs = new Set<string>()
  if (!templateSource.includes('ref=')) return []

  try {
    const ast = baseParse(`<template>${templateSource}</template>`)
    walkVueTemplateElements(ast, node => {
      for (const prop of node.props ?? []) {
        if (prop.type === NodeTypes.ATTRIBUTE && prop.name === 'ref' && prop.value?.content) {
          refs.add(prop.value.content)
        }
      }
    })
  } catch {
    return []
  }

  return [...refs]
}

function normalizeInlineVueTemplateBindings(templateSource: string): NormalizedInlineTemplate {
  const bindings = new Map<string, InlineVueBinding>()
  const locals = collectInlineNovaTemplateLocals(templateSource)

  const addBinding = (propName: string, expression = propName): void => {
    if (!bindings.has(propName)) bindings.set(propName, { propName, expression })
  }

  let source = templateSource.replace(
    /((?::for|for)="[^"]+\s(?:in|of)\s+)([A-Za-z_$][\w$]*)(")/g,
    (match, prefix: string, name: string, suffix: string) => {
      if (isImplicitNovaTemplateBinding(name) || locals.has(name)) return match
      addBinding(name)
      return `${prefix}props.${name}${suffix}`
    },
  )

  source = source.replace(
    /((?::[\w-]+|if|else-if)=")([A-Za-z_$][\w$]*)(")/g,
    (match, prefix: string, name: string, suffix: string) => {
      if (isImplicitNovaTemplateBinding(name) || locals.has(name)) return match
      addBinding(name)
      return `${prefix}props.${name}${suffix}`
    },
  )

  source = source.replace(
    /(@[\w:-]+=")([A-Za-z_$][\w$]*)(")/g,
    (match, prefix: string, name: string, suffix: string) => {
      if (isImplicitNovaTemplateBinding(name) || locals.has(name)) return match
      const propName = `novaHandler${capitalizeIdentifier(name)}`
      addBinding(propName, name)
      return `${prefix}props.${propName}${suffix}`
    },
  )

  return {
    source,
    bindings: [...bindings.values()],
  }
}

function collectInlineNovaTemplateLocals(templateSource: string): Set<string> {
  const locals = new Set<string>()

  try {
    const ast = baseParse(`<template>${templateSource}</template>`)
    walkVueTemplateElements(ast, node => {
      for (const prop of node.props ?? []) {
        if (prop.type !== NodeTypes.DIRECTIVE) continue

        if (prop.name === 'for' && prop.exp?.content) {
          collectVForLocals(prop.exp.content, locals)
          continue
        }

        if (prop.name === 'bind' && prop.arg?.content === 'for' && prop.exp?.content) {
          collectVForLocals(prop.exp.content, locals)
          continue
        }

        if ((prop.name === 'bind' || prop.name === 'on') && prop.exp?.content) {
          continue
        }

        if (prop.name === 'slot' && prop.exp?.content) {
          collectExpressionLocals(prop.exp.content, locals)
        }
      }

      for (const prop of node.props ?? []) {
        if (prop.type !== NodeTypes.ATTRIBUTE || prop.name !== 'for' || !prop.value?.content) continue
        collectVForLocals(prop.value.content, locals)
      }
    })
  } catch {
    return locals
  }

  return locals
}

function collectVForLocals(source: string, locals: Set<string>): void {
  const match = source.match(/^\s*(?:\(([^)]*)\)|([A-Za-z_$][\w$]*))\s+(?:in|of)\s+/)
  const aliases = match?.[1] ?? match?.[2]
  if (!aliases) return

  for (const alias of aliases.split(',')) {
    const name = alias.trim()
    if (/^[A-Za-z_$][\w$]*$/.test(name)) locals.add(name)
  }
}

function collectExpressionLocals(source: string, locals: Set<string>): void {
  const identifiers = source.match(/[A-Za-z_$][\w$]*/g) ?? []
  for (const identifier of identifiers) {
    if (!isImplicitNovaTemplateBinding(identifier)) locals.add(identifier)
  }
}

function isImplicitNovaTemplateBinding(name: string): boolean {
  return ['canvas', 'props', 'width', 'height', 'styleSheet', 'true', 'false', 'null', 'undefined'].includes(name)
}

function toKebabCase(value: string): string {
  return value.replace(/[A-Z]/g, char => `-${char.toLowerCase()}`)
}

function capitalizeIdentifier(value: string): string {
  return value ? `${value[0].toUpperCase()}${value.slice(1)}` : value
}

function applyReplacements(source: string, replacements: Array<Replacement>): string {
  let transformed = source
  const ordered = [...replacements].sort((a, b) => b.start - a.start)

  for (const replacement of ordered) {
    transformed = `${transformed.slice(0, replacement.start)}${replacement.value}${transformed.slice(replacement.end)}`
  }

  return transformed
}

function clearVueInlineVirtualModules(virtualModules: Map<string, VirtualNovaModule>, ownerFile: string): void {
  for (const [id, module] of virtualModules.entries()) {
    if (module.ownerFile === ownerFile) virtualModules.delete(id)
  }
}

function withVirtualVersion(importSource: string, source: string): string {
  return `${importSource}?v=${hashString(source)}`
}

function parseAttrs(source: string): Array<ParsedAttr> {
  const attrs: Array<ParsedAttr> = []
  const pattern = /([#:@.\w-]+)(?:=(?:"([^"]*)"|'([^']*)'))?/g
  let match: RegExpExecArray | null

  while ((match = pattern.exec(source)) !== null) {
    attrs.push({
      name: match[1],
      value: match[2] ?? match[3] ?? true,
    })
  }

  return attrs
}

function readParsedAttr(attrs: ReadonlyArray<ParsedAttr>, name: string): string | undefined {
  const attr = attrs.find(item => item.name === name)
  return typeof attr?.value === 'string' ? attr.value : undefined
}

function injectVueScriptSetupImports(source: string, imports: string): string {
  const setupPattern = /<script\b([^>]*)\bsetup\b([^>]*)>/i
  const match = setupPattern.exec(source)
  if (!match) {
    return `<script setup>\n${imports}\n</script>\n${source}`
  }

  const insertAt = match.index + match[0].length
  return `${source.slice(0, insertAt)}\n${imports}${source.slice(insertAt)}`
}

function resolveGeneratedOutputOptions(options: NovaGeneratedOutputOptions = {}): Required<NovaGeneratedOutputOptions> {
  return {
    enabled: options.enabled ?? process.env[NOVA_GEN_DEBUG_ENV] === 'true',
    dir: options.dir ?? DEFAULT_GENERATED_OUTPUT_DIR,
  }
}

function resolveSourceImport(
  request: string,
  from: string | undefined,
  context: { addWatchFile: (id: string) => void },
): { source: string; filename: string } | null {
  const baseDir = from ? path.dirname(stripViteQuery(from)) : process.cwd()
  const resolved = request.startsWith('@/') || request === '@'
    ? path.resolve(process.cwd(), 'src', request.slice(2))
    : path.resolve(baseDir, request)
  if (!fs.existsSync(resolved)) return null
  context.addWatchFile(resolved)
  return {
    source: fs.readFileSync(resolved, 'utf8'),
    filename: resolved,
  }
}

function writeGeneratedOutput(
  generatedOutput: Required<NovaGeneratedOutputOptions>,
  sourceId: string,
  code: string,
): void {
  if (!generatedOutput.enabled) return

  const outputPath = resolveGeneratedOutputPath(generatedOutput.dir, sourceId)
  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, `${GENERATED_OUTPUT_HEADER}${code}`, 'utf8')
}

function resolveGeneratedOutputPath(outputDir: string, sourceId: string): string {
  const root = process.cwd()
  const sourcePath = stripViteQuery(sourceId)
  const normalizedSourcePath = path.normalize(sourcePath)
  let relativePath = path.isAbsolute(normalizedSourcePath)
    ? path.relative(root, normalizedSourcePath)
    : normalizedSourcePath

  if (relativePath.startsWith('..') || path.isAbsolute(relativePath)) {
    relativePath = path.join('__external__', normalizedSourcePath.replace(/^[A-Za-z]:/, '').replace(/^[/\\]+/, ''))
  }

  const safeRelativePath = relativePath
    .split(path.sep)
    .map(segment => segment.replace(/[<>:"|?*]/g, '_'))
    .join(path.sep)

  return path.resolve(root, outputDir, `${safeRelativePath}.ts`)
}

function stripViteQuery(id: string): string {
  return id.split('?')[0]
}

function hasViteQuery(id: string, name: string): boolean {
  const query = id.split('?')[1]
  if (!query) return false
  return new URLSearchParams(query).has(name)
}

function isVueSubBlockRequest(id: string): boolean {
  return id.includes('?vue') || id.includes('&vue')
}

function hashString(value: string): string {
  let hash = 2166136261

  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index)
    hash = Math.imul(hash, 16777619)
  }

  return (hash >>> 0).toString(36)
}

function escapeAttr(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;')
}

function throwOnErrors(
  diagnostics: Array<{ severity: string; code: string; message: string; line?: number; column?: number }>,
): void {
  const error = diagnostics.find(item => item.severity === 'error')
  if (!error) return
  throw new Error(`${error.code}: ${error.message}`)
}

function emitDiagnostics(
  id: string,
  diagnostics: Array<{ severity: string; code: string; message: string; line?: number; column?: number }>,
  enabled: boolean,
): void {
  if (!enabled) return
  for (const diagnostic of diagnostics) {
    const location = diagnostic.line ? `${diagnostic.line}:${diagnostic.column ?? 1}` : '0:0'
    const message = `[${id}:${location}] ${diagnostic.code}: ${diagnostic.message}`
    if (diagnostic.severity === 'error') {
      console.error(message)
    } else {
      console.warn(message)
    }
  }
}
