import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import type { Plugin } from 'vite'
import { novaVitePlugin } from '@/vite/novaVitePlugin'

const TEMP_DIRS: Array<string> = []

describe('Nova Vite plugin generated debug output', () => {
  afterEach(() => {
    delete process.env.NOVA_GEN_DEBUG_ENABLED
    for (const dir of TEMP_DIRS.splice(0)) {
      fs.rmSync(dir, { recursive: true, force: true })
    }
  })

  it('does not write generated files when debug output is disabled', async () => {
    const outputDir = createTempDir()
    const plugin = novaVitePlugin({
      generatedOutput: {
        enabled: false,
        dir: outputDir,
      },
    })

    await runTransform(plugin, '<template><Root /></template>', sourcePath('src/fixtures/Disabled.nova'))

    expect(fs.existsSync(outputDir)).toBe(false)
  })

  it('writes .nova and .novacss generated files when env flag is enabled', async () => {
    process.env.NOVA_GEN_DEBUG_ENABLED = 'true'
    const outputDir = createTempDir()
    const plugin = novaVitePlugin({
      generatedOutput: {
        dir: outputDir,
      },
    })

    await runTransform(plugin, '<template><Root /></template>', sourcePath('src/fixtures/Demo.nova'))
    await runTransform(plugin, 'Root.demo { color: #111111; }', sourcePath('src/fixtures/Demo.novacss'))

    const sfcOutput = path.join(outputDir, 'src/fixtures/Demo.nova.ts')
    const cssOutput = path.join(outputDir, 'src/fixtures/Demo.novacss.ts')

    expect(fs.readFileSync(sfcOutput, 'utf8')).toContain('Generated by @endge/nova-compiler')
    expect(fs.readFileSync(sfcOutput, 'utf8')).toContain('export default class Demo extends NovaNode')
    expect(fs.readFileSync(cssOutput, 'utf8')).toContain('const asset =')
  })

  it('transforms #nova-template slot into a virtual module import', async () => {
    const outputDir = createTempDir()
    const plugin = novaVitePlugin({
      generatedOutput: {
        enabled: true,
        dir: outputDir,
      },
    })

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><template #nova-template><Root /></template></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    expect(result).toMatchObject({
      map: null,
    })
    const code = (result as { code: string }).code
    expect(code).toContain('import __NovaTemplate0')
    expect(code).toContain(':component="__NovaTemplate0"')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()
    expect(virtualId).toContain('?v=')
    await runLoad(plugin, virtualId!)

    const inlineOutput = path.join(outputDir, 'src/pages/Page.vue__nova_template_0.nova.ts')

    expect(fs.readFileSync(inlineOutput, 'utf8')).toContain('export default class PageVueNovaTemplate0 extends NovaNode')
  })

  it('versions inline #nova-template virtual imports when Vue source changes', async () => {
    const plugin = novaVitePlugin()
    const file = sourcePath('src/pages/Page.vue')

    const first = await runTransform(
      plugin,
      '<template><NovaCanvas><template #nova-template><Root id="first-template" /></template></NovaCanvas></template>',
      file,
    )
    const firstCode = (first as { code: string }).code
    const firstVirtualId = firstCode.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]

    const second = await runTransform(
      plugin,
      '<template><NovaCanvas><template #nova-template><Root id="second-template" /></template></NovaCanvas></template>',
      file,
    )
    const secondCode = (second as { code: string }).code
    const secondVirtualId = secondCode.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]

    expect(firstVirtualId).toBeTruthy()
    expect(secondVirtualId).toBeTruthy()
    expect(secondVirtualId).not.toBe(firstVirtualId)

    const compiled = await runLoad(plugin, secondVirtualId!)
    expect(compiled).toContain('second-template')
    expect(compiled).not.toContain('first-template')
  })

  it('moves Vue novacss style blocks into inline nova-template virtual modules', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <template>
          <NovaCanvas>
            <template #nova-template>
              <Root class="screen">
                <TextBlock class="title" text="Demo" />
              </Root>
            </template>
          </NovaCanvas>
        </template>

        <style lang="novacss" scoped>
        Root.screen { background: #ffffff; }
        TextBlock.title { color: #111111; }
        </style>

        <style>
        .page { display: block; }
        </style>
      `,
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).not.toContain('lang="novacss"')
    expect(code).toContain('.page { display: block; }')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('styleSheet:__novaSfcStyle')
    expect(compiled).toContain('#111111')
  })

  it('treats lang novascc as a compatibility alias for novacss', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <template>
          <NovaCanvas>
            <template #nova-template>
              <Root class="screen" />
            </template>
          </NovaCanvas>
        </template>

        <style lang="novascc">
        Root.screen { background: #ffffff; }
        </style>
      `,
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).not.toContain('lang="novascc"')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('#ffffff')
  })

  it('transforms #nova-template src into a static component import and keeps attrs', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><template #nova-template src="@/demo/Chart.nova" :options="options" @select="onSelect"><Root /></template></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain('import __NovaTemplate0 from "@/demo/Chart.nova"')
    expect(code).toContain('source="@/demo/Chart.nova"')
    expect(code).toContain(':options="options"')
    expect(code).toContain('@select="onSelect"')
    expect(code).not.toContain('<Root />')
  })

  it('does not transform legacy source nova-template tags anymore', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><nova-template><Root /></nova-template></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    expect(result).toBeNull()
  })
})

async function runTransform(plugin: Plugin, source: string, id: string): Promise<unknown> {
  const transform = plugin.transform
  const context = {
    addWatchFile() {},
  }

  if (typeof transform === 'function') {
    return await transform.call(context as never, source, id)
  }

  return await transform?.handler.call(context as never, source, id)
}

async function runLoad(plugin: Plugin, id: string): Promise<unknown> {
  const load = plugin.load
  const context = {
    addWatchFile() {},
  }

  if (typeof load === 'function') {
    return await load.call(context as never, id)
  }

  return await load?.handler.call(context as never, id)
}

function createTempDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nova-compiler-'))
  fs.rmSync(dir, { recursive: true, force: true })
  TEMP_DIRS.push(dir)
  return dir
}

function sourcePath(relativePath: string): string {
  return path.join(process.cwd(), relativePath)
}
