import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'
import { compileNovaCss, generateNovaCssModule } from '@/css/NovaCssCompiler'
import { compileNovaSfc } from '@/sfc/NovaSfcCompiler'

export interface NovaGeneratedOutputOptions {
  enabled?: boolean
  dir?: string
}

export interface NovaVitePluginOptions {
  includeDiagnostics?: boolean
  generatedOutput?: NovaGeneratedOutputOptions
}

interface VirtualNovaModule {
  source: string
  filename: string
  ownerFile: string
}

interface ParsedAttr {
  name: string
  value: string | true
}

const NOVA_GEN_DEBUG_ENV = 'NOVA_GEN_DEBUG_ENABLED'
const DEFAULT_GENERATED_OUTPUT_DIR = '.nova-generated'
const GENERATED_OUTPUT_HEADER = '// Generated by @endge/nova-compiler. Do not edit.\n\n'

/** Vite plugin для `.nova`, `.novacss` и Vue `<nova-template>`. */
export function novaVitePlugin(options: NovaVitePluginOptions = {}): Plugin {
  const generatedOutput = resolveGeneratedOutputOptions(options.generatedOutput)
  const virtualModules = new Map<string, VirtualNovaModule>()

  return {
    name: 'endge-nova-compiler',
    enforce: 'pre',

    resolveId(id) {
      if (virtualModules.has(stripViteQuery(id))) return id
      return null
    },

    load(id) {
      const virtualModule = virtualModules.get(stripViteQuery(id))
      if (!virtualModule) return null
      return compileNovaModule(virtualModule.source, virtualModule.filename, this, options, generatedOutput)
    },

    transform(source, id) {
      const cleanId = stripViteQuery(id)

      if (virtualModules.has(id)) {
        return null
      }

      if (cleanId.endsWith('.novacss')) {
        const result = compileNovaCss(source, {
          filename: cleanId,
          resolveImport: (request, from) => resolveSourceImport(request, from, this),
        })
        const code = generateNovaCssModule(result)
        emitDiagnostics(cleanId, result.diagnostics, options.includeDiagnostics ?? true)
        throwOnErrors(result.diagnostics)
        writeGeneratedOutput(generatedOutput, cleanId, code)
        return {
          code,
          map: null,
        }
      }

      if (cleanId.endsWith('.nova')) {
        return {
          code: compileNovaModule(source, cleanId, this, options, generatedOutput),
          map: null,
        }
      }

      if (cleanId.endsWith('.vue')) {
        clearVueInlineVirtualModules(virtualModules, cleanId)
        const transformed = transformVueNovaTemplates(source, cleanId, virtualModules, options.includeDiagnostics ?? true)
        if (transformed) {
          writeGeneratedOutput(generatedOutput, `${cleanId}__nova_template_transform`, transformed)
          return {
            code: transformed,
            map: null,
          }
        }
      }

      return null
    },
  }
}

function compileNovaModule(
  source: string,
  id: string,
  context: { addWatchFile: (id: string) => void },
  options: NovaVitePluginOptions,
  generatedOutput: Required<NovaGeneratedOutputOptions>,
): string {
  const result = compileNovaSfc(source, {
    filename: id,
    resolveImport: (request, from) => resolveSourceImport(request, from, context),
  })
  emitDiagnostics(id, result.diagnostics, options.includeDiagnostics ?? true)
  throwOnErrors(result.diagnostics)
  writeGeneratedOutput(generatedOutput, id, result.code)
  return result.code
}

function transformVueNovaTemplates(
  source: string,
  id: string,
  virtualModules: Map<string, VirtualNovaModule>,
  includeDiagnostics: boolean,
): string | null {
  const imports: Array<string> = []
  let index = 0
  let changed = false
  const transformed = source.replace(
    /<nova-template\b([^>]*?)(\/>|>([\s\S]*?)<\/nova-template>)/g,
    (_raw: string, attrsSource: string, _close: string, children: string | undefined) => {
      const attrs = parseAttrs(attrsSource)
      const src = readParsedAttr(attrs, 'src')
      const componentName = `__NovaTemplate${index}`
      const debugId = `${stripViteQuery(id)}__nova_template_${index}`
      let importSource: string

      if (src) {
        importSource = src
        if (children?.trim()) {
          emitDiagnostics(id, [{
            severity: 'warning',
            code: 'nova-template-src-ignores-children',
            message: '<nova-template src="..."> игнорирует внутреннее содержимое.',
          }], includeDiagnostics)
        }
      } else {
        importSource = `virtual:nova-template:${stripViteQuery(id)}:${index}.nova`
        virtualModules.set(importSource, {
          filename: `${stripViteQuery(id)}__nova_template_${index}.nova`,
          source: `<template>\n${children?.trim() ?? ''}\n</template>`,
          ownerFile: stripViteQuery(id),
        })
      }

      const importModuleSource = src ? importSource : withVirtualVersion(importSource, children?.trim() ?? '')
      imports.push(`import ${componentName} from ${JSON.stringify(importModuleSource)};`)
      changed = true
      index += 1

      const forwardedAttrs = attrs
        .filter(attr => attr.name !== 'src')
        .map(serializeVueAttr)
        .filter(Boolean)
      return `<nova-template :component="${componentName}" source="${escapeAttr(src ?? importSource)}" debug-id="${escapeAttr(debugId)}"${forwardedAttrs.length ? ` ${forwardedAttrs.join(' ')}` : ''} />`
    },
  )

  if (!changed) return null
  return injectVueScriptSetupImports(transformed, imports.join('\n'))
}

function clearVueInlineVirtualModules(virtualModules: Map<string, VirtualNovaModule>, ownerFile: string): void {
  for (const [id, module] of virtualModules.entries()) {
    if (module.ownerFile === ownerFile) virtualModules.delete(id)
  }
}

function withVirtualVersion(importSource: string, source: string): string {
  return `${importSource}?v=${hashString(source)}`
}

function parseAttrs(source: string): Array<ParsedAttr> {
  const attrs: Array<ParsedAttr> = []
  const pattern = /([:@.\w-]+)(?:=(?:"([^"]*)"|'([^']*)'))?/g
  let match: RegExpExecArray | null

  while ((match = pattern.exec(source)) !== null) {
    attrs.push({
      name: match[1],
      value: match[2] ?? match[3] ?? true,
    })
  }

  return attrs
}

function readParsedAttr(attrs: ReadonlyArray<ParsedAttr>, name: string): string | undefined {
  const attr = attrs.find(item => item.name === name)
  return typeof attr?.value === 'string' ? attr.value : undefined
}

function serializeVueAttr(attr: ParsedAttr): string {
  if (attr.value === true) return attr.name
  return `${attr.name}="${escapeAttr(attr.value)}"`
}

function injectVueScriptSetupImports(source: string, imports: string): string {
  const setupPattern = /<script\b([^>]*)\bsetup\b([^>]*)>/i
  const match = setupPattern.exec(source)
  if (!match) {
    return `<script setup>\n${imports}\n</script>\n${source}`
  }

  const insertAt = match.index + match[0].length
  return `${source.slice(0, insertAt)}\n${imports}${source.slice(insertAt)}`
}

function resolveGeneratedOutputOptions(options: NovaGeneratedOutputOptions = {}): Required<NovaGeneratedOutputOptions> {
  return {
    enabled: options.enabled ?? process.env[NOVA_GEN_DEBUG_ENV] === 'true',
    dir: options.dir ?? DEFAULT_GENERATED_OUTPUT_DIR,
  }
}

function resolveSourceImport(
  request: string,
  from: string | undefined,
  context: { addWatchFile: (id: string) => void },
): { source: string; filename: string } | null {
  const baseDir = from ? path.dirname(stripViteQuery(from)) : process.cwd()
  const resolved = request.startsWith('@/') || request === '@'
    ? path.resolve(process.cwd(), 'src', request.slice(2))
    : path.resolve(baseDir, request)
  if (!fs.existsSync(resolved)) return null
  context.addWatchFile(resolved)
  return {
    source: fs.readFileSync(resolved, 'utf8'),
    filename: resolved,
  }
}

function writeGeneratedOutput(
  generatedOutput: Required<NovaGeneratedOutputOptions>,
  sourceId: string,
  code: string,
): void {
  if (!generatedOutput.enabled) return

  const outputPath = resolveGeneratedOutputPath(generatedOutput.dir, sourceId)
  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, `${GENERATED_OUTPUT_HEADER}${code}`, 'utf8')
}

function resolveGeneratedOutputPath(outputDir: string, sourceId: string): string {
  const root = process.cwd()
  const sourcePath = stripViteQuery(sourceId)
  const normalizedSourcePath = path.normalize(sourcePath)
  let relativePath = path.isAbsolute(normalizedSourcePath)
    ? path.relative(root, normalizedSourcePath)
    : normalizedSourcePath

  if (relativePath.startsWith('..') || path.isAbsolute(relativePath)) {
    relativePath = path.join('__external__', normalizedSourcePath.replace(/^[A-Za-z]:/, '').replace(/^[/\\]+/, ''))
  }

  const safeRelativePath = relativePath
    .split(path.sep)
    .map(segment => segment.replace(/[<>:"|?*]/g, '_'))
    .join(path.sep)

  return path.resolve(root, outputDir, `${safeRelativePath}.ts`)
}

function stripViteQuery(id: string): string {
  return id.split('?')[0]
}

function hashString(value: string): string {
  let hash = 2166136261

  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index)
    hash = Math.imul(hash, 16777619)
  }

  return (hash >>> 0).toString(36)
}

function escapeAttr(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;')
}

function throwOnErrors(
  diagnostics: Array<{ severity: string; code: string; message: string; line?: number; column?: number }>,
): void {
  const error = diagnostics.find(item => item.severity === 'error')
  if (!error) return
  throw new Error(`${error.code}: ${error.message}`)
}

function emitDiagnostics(
  id: string,
  diagnostics: Array<{ severity: string; code: string; message: string; line?: number; column?: number }>,
  enabled: boolean,
): void {
  if (!enabled) return
  for (const diagnostic of diagnostics) {
    const location = diagnostic.line ? `${diagnostic.line}:${diagnostic.column ?? 1}` : '0:0'
    const message = `[${id}:${location}] ${diagnostic.code}: ${diagnostic.message}`
    if (diagnostic.severity === 'error') {
      console.error(message)
    } else {
      console.warn(message)
    }
  }
}
