import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'
import { compileNovaCss, generateNovaCssModule } from '@/css/NovaCssCompiler'
import { compileNovaSfc } from '@/sfc/NovaSfcCompiler'

export interface NovaGeneratedOutputOptions {
  enabled?: boolean
  dir?: string
}

export interface NovaVitePluginOptions {
  includeDiagnostics?: boolean
  generatedOutput?: NovaGeneratedOutputOptions
}

const NOVA_GEN_DEBUG_ENV = 'NOVA_GEN_DEBUG_ENABLED'
const DEFAULT_GENERATED_OUTPUT_DIR = '.nova-generated'
const GENERATED_OUTPUT_HEADER = '// Generated by @endge/nova-compiler. Do not edit.\n\n'

/** Vite plugin для `.nova` и `.novacss`. */
export function novaVitePlugin(options: NovaVitePluginOptions = {}): Plugin {
  const generatedOutput = resolveGeneratedOutputOptions(options.generatedOutput)

  return {
    name: 'endge-nova-compiler',
    enforce: 'pre',
    transform(source, id) {
      const resolveCssImport = (request: string, from: string | undefined): string | null => {
        const baseDir = from ? path.dirname(from) : process.cwd()
        const resolved = path.resolve(baseDir, request)
        if (!fs.existsSync(resolved)) return null
        this.addWatchFile(resolved)
        return fs.readFileSync(resolved, 'utf8')
      }

      if (id.endsWith('.novacss')) {
        const result = compileNovaCss(source, {
          filename: id,
          resolveImport: resolveCssImport,
        })
        const code = generateNovaCssModule(result)
        emitDiagnostics(id, result.diagnostics, options.includeDiagnostics ?? true)
        throwOnErrors(result.diagnostics)
        writeGeneratedOutput(generatedOutput, id, code)
        return {
          code,
          map: null,
        }
      }

      if (id.endsWith('.nova')) {
        const result = compileNovaSfc(source, {
          filename: id,
          resolveImport: resolveCssImport,
        })
        emitDiagnostics(id, result.diagnostics, options.includeDiagnostics ?? true)
        throwOnErrors(result.diagnostics)
        writeGeneratedOutput(generatedOutput, id, result.code)
        return {
          code: result.code,
          map: null,
        }
      }

      if (id.endsWith('.vue')) {
        dumpInlineNovaTemplates(source, id, generatedOutput, options.includeDiagnostics ?? true)
      }

      return null
    },
  }
}

function resolveGeneratedOutputOptions(options: NovaGeneratedOutputOptions = {}): Required<NovaGeneratedOutputOptions> {
  return {
    enabled: options.enabled ?? process.env[NOVA_GEN_DEBUG_ENV] === 'true',
    dir: options.dir ?? DEFAULT_GENERATED_OUTPUT_DIR,
  }
}

function dumpInlineNovaTemplates(
  source: string,
  id: string,
  generatedOutput: Required<NovaGeneratedOutputOptions>,
  includeDiagnostics: boolean,
): void {
  const templatePattern = /<nova-template\b[^>]*>([\s\S]*?)<\/nova-template>/g
  let match: RegExpExecArray | null
  let index = 0

  while ((match = templatePattern.exec(source)) !== null) {
    const virtualId = `${stripViteQuery(id)}__nova_template_${index}.nova`
    const result = compileNovaSfc(`<template>\n${match[1].trim()}\n</template>`, {
      filename: virtualId,
    })

    emitDiagnostics(virtualId, result.diagnostics, includeDiagnostics)
    writeGeneratedOutput(generatedOutput, virtualId, result.code)
    index += 1
  }
}

function writeGeneratedOutput(
  generatedOutput: Required<NovaGeneratedOutputOptions>,
  sourceId: string,
  code: string,
): void {
  if (!generatedOutput.enabled) return

  const outputPath = resolveGeneratedOutputPath(generatedOutput.dir, sourceId)
  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, `${GENERATED_OUTPUT_HEADER}${code}`, 'utf8')
}

function resolveGeneratedOutputPath(outputDir: string, sourceId: string): string {
  const root = process.cwd()
  const sourcePath = stripViteQuery(sourceId)
  const normalizedSourcePath = path.normalize(sourcePath)
  let relativePath = path.isAbsolute(normalizedSourcePath)
    ? path.relative(root, normalizedSourcePath)
    : normalizedSourcePath

  if (relativePath.startsWith('..') || path.isAbsolute(relativePath)) {
    relativePath = path.join('__external__', normalizedSourcePath.replace(/^[A-Za-z]:/, '').replace(/^[/\\]+/, ''))
  }

  const safeRelativePath = relativePath
    .split(path.sep)
    .map(segment => segment.replace(/[<>:"|?*]/g, '_'))
    .join(path.sep)

  return path.resolve(root, outputDir, `${safeRelativePath}.ts`)
}

function stripViteQuery(id: string): string {
  return id.split('?')[0]
}

function throwOnErrors(
  diagnostics: Array<{ severity: string; code: string; message: string; line?: number; column?: number }>,
): void {
  const error = diagnostics.find(item => item.severity === 'error')
  if (!error) return
  throw new Error(`${error.code}: ${error.message}`)
}

function emitDiagnostics(
  id: string,
  diagnostics: Array<{ severity: string; code: string; message: string; line?: number; column?: number }>,
  enabled: boolean,
): void {
  if (!enabled) return
  for (const diagnostic of diagnostics) {
    const location = diagnostic.line ? `${diagnostic.line}:${diagnostic.column ?? 1}` : '0:0'
    const message = `[${id}:${location}] ${diagnostic.code}: ${diagnostic.message}`
    if (diagnostic.severity === 'error') {
      console.error(message)
    } else {
      console.warn(message)
    }
  }
}
