import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import type { Plugin } from 'vite'
import { novaVitePlugin } from '@/vite/novaVitePlugin'

const TEMP_DIRS: Array<string> = []

describe('Nova Vite plugin generated debug output', () => {
  afterEach(() => {
    delete process.env.NOVA_GEN_DEBUG_ENABLED
    for (const dir of TEMP_DIRS.splice(0)) {
      fs.rmSync(dir, { recursive: true, force: true })
    }
  })

  it('does not write generated files when debug output is disabled', async () => {
    const outputDir = createTempDir()
    const plugin = novaVitePlugin({
      generatedOutput: {
        enabled: false,
        dir: outputDir,
      },
    })

    await runTransform(plugin, '<template><Root /></template>', sourcePath('src/fixtures/Disabled.nova'))

    expect(fs.existsSync(outputDir)).toBe(false)
  })

  it('writes .nova and .novacss generated files when env flag is enabled', async () => {
    process.env.NOVA_GEN_DEBUG_ENABLED = 'true'
    const outputDir = createTempDir()
    const plugin = novaVitePlugin({
      generatedOutput: {
        dir: outputDir,
      },
    })

    await runTransform(plugin, '<template><Root /></template>', sourcePath('src/fixtures/Demo.nova'))
    await runTransform(plugin, 'Root.demo { color: #111111; }', sourcePath('src/fixtures/Demo.novacss'))

    const sfcOutput = path.join(outputDir, 'src/fixtures/Demo.nova.ts')
    const cssOutput = path.join(outputDir, 'src/fixtures/Demo.novacss.ts')

    expect(fs.readFileSync(sfcOutput, 'utf8')).toContain('Generated by @endge/nova-compiler')
    expect(fs.readFileSync(sfcOutput, 'utf8')).toContain('export default class Demo extends NovaNode')
    expect(fs.readFileSync(cssOutput, 'utf8')).toContain('const asset =')
  })

  it('writes inline nova-template generated files without replacing the Vue transform', async () => {
    const outputDir = createTempDir()
    const plugin = novaVitePlugin({
      generatedOutput: {
        enabled: true,
        dir: outputDir,
      },
    })

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><nova-template><Root /></nova-template></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    const inlineOutput = path.join(outputDir, 'src/pages/Page.vue__nova_template_0.nova.ts')

    expect(result).toBeNull()
    expect(fs.readFileSync(inlineOutput, 'utf8')).toContain('export default class PageVueNovaTemplate0 extends NovaNode')
  })
})

async function runTransform(plugin: Plugin, source: string, id: string): Promise<unknown> {
  const transform = plugin.transform
  const context = {
    addWatchFile() {},
  }

  if (typeof transform === 'function') {
    return await transform.call(context as never, source, id)
  }

  return await transform?.handler.call(context as never, source, id)
}

function createTempDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nova-compiler-'))
  fs.rmSync(dir, { recursive: true, force: true })
  TEMP_DIRS.push(dir)
  return dir
}

function sourcePath(relativePath: string): string {
  return path.join(process.cwd(), relativePath)
}
