import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import type { Plugin } from 'vite'
import { novaVitePlugin } from '@/vite/novaVitePlugin'

const TEMP_DIRS: Array<string> = []

describe('Nova Vite plugin generated debug output', () => {
  afterEach(() => {
    delete process.env.NOVA_GEN_DEBUG_ENABLED
    for (const dir of TEMP_DIRS.splice(0)) {
      fs.rmSync(dir, { recursive: true, force: true })
    }
  })

  it('does not write generated files when debug output is disabled', async () => {
    const outputDir = createTempDir()
    const plugin = novaVitePlugin({
      generatedOutput: {
        enabled: false,
        dir: outputDir,
      },
    })

    await runTransform(plugin, '<template><Root /></template>', sourcePath('src/fixtures/Disabled.nova'))

    expect(fs.existsSync(outputDir)).toBe(false)
  })

  it('writes .nova and .novacss generated files when env flag is enabled', async () => {
    process.env.NOVA_GEN_DEBUG_ENABLED = 'true'
    const outputDir = createTempDir()
    const plugin = novaVitePlugin({
      generatedOutput: {
        dir: outputDir,
      },
    })

    await runTransform(plugin, '<template><Root /></template>', sourcePath('src/fixtures/Demo.nova'))
    await runTransform(plugin, 'Root.demo { color: #111111; }', sourcePath('src/fixtures/Demo.novacss'))

    const sfcOutput = path.join(outputDir, 'src/fixtures/Demo.nova.ts')
    const cssOutput = path.join(outputDir, 'src/fixtures/Demo.novacss.ts')

    expect(fs.readFileSync(sfcOutput, 'utf8')).toContain('Generated by @endge/nova-compiler')
    expect(fs.readFileSync(sfcOutput, 'utf8')).toContain('export default class Demo extends NovaNode')
    expect(fs.readFileSync(cssOutput, 'utf8')).toContain('const asset =')
  })

  it('generates global registration for bare .novacss imports', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '@theme light { --nova-scene-bg: #ffffff; }',
      sourcePath('src/fixtures/theme.novacss'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain('import { Nova } from \'@endge/nova\'')
    expect(code).toContain('Nova.import(asset)')
    expect(code).toContain('export const themes = asset.themes ?? []')
  })

  it('returns a plain asset for .novacss?asset imports', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '@theme light { --nova-scene-bg: #ffffff; }',
      `${sourcePath('src/fixtures/theme.novacss')}?asset`,
    )

    const code = (result as { code: string }).code
    expect(code).not.toContain('Nova.import(asset)')
    expect(code).toContain('export default asset')
  })

  it('transforms NovaCanvas default slot DSL into a virtual module import', async () => {
    const outputDir = createTempDir()
    const plugin = novaVitePlugin({
      generatedOutput: {
        enabled: true,
        dir: outputDir,
      },
    })

    const result = await runTransform(
      plugin,
      '<script setup lang="ts">const timeline = Nova.ref(); const initialData = []</script><template><NovaCanvas><TimelineChart.Root ref="timeline" :data="initialData" /></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    expect(result).toMatchObject({
      map: null,
    })
    const code = (result as { code: string }).code
    expect(code).toContain('import __NovaTemplate0')
    expect(code).toContain(':component="__NovaTemplate0"')
    expect(code).toContain(':nova-refs="{ timeline }"')
    expect(code).toContain(':initial-data="initialData"')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()
    expect(virtualId).toContain('?v=')
    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('registerNovaUIKit(app.schema)')
    expect(compiled).toContain('__ensureNovaUiKit(app)')
    expect(compiled).toContain('type:__NovaUIKit.Root')
    expect(compiled).toContain('width:props.width')
    expect(compiled).toContain('data:props.initialData')
    expect(compiled).toContain('ref:"timeline"')

    const inlineOutput = path.join(outputDir, 'src/pages/Page.vue__nova_template_0.nova.ts')

    expect(fs.readFileSync(inlineOutput, 'utf8')).toContain('export default class PageVueNovaTemplate0 extends NovaNode')
  })

  it('versions inline NovaCanvas virtual imports when Vue source changes', async () => {
    const plugin = novaVitePlugin()
    const file = sourcePath('src/pages/Page.vue')

    const first = await runTransform(
      plugin,
      '<template><NovaCanvas><Root id="first-template" /></NovaCanvas></template>',
      file,
    )
    const firstCode = (first as { code: string }).code
    const firstVirtualId = firstCode.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]

    const second = await runTransform(
      plugin,
      '<template><NovaCanvas><Root id="second-template" /></NovaCanvas></template>',
      file,
    )
    const secondCode = (second as { code: string }).code
    const secondVirtualId = secondCode.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]

    expect(firstVirtualId).toBeTruthy()
    expect(secondVirtualId).toBeTruthy()
    expect(secondVirtualId).not.toBe(firstVirtualId)

    const compiled = await runLoad(plugin, secondVirtualId!)
    expect(compiled).toContain('second-template')
    expect(compiled).not.toContain('first-template')
  })

  it('keeps inline NovaCanvas virtual module when Vue script block is transformed', async () => {
    const plugin = novaVitePlugin()
    const file = sourcePath('src/pages/Page.vue')

    const result = await runTransform(
      plugin,
      '<script setup lang="ts">const label = "Demo"</script><template><NovaCanvas><Root id="inline-template" /></NovaCanvas></template>',
      file,
    )
    const code = (result as { code: string }).code
    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]

    expect(virtualId).toBeTruthy()

    await runTransform(
      plugin,
      'const label = "Demo"',
      `${file}?vue&type=script&setup=true&lang.ts`,
    )

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('inline-template')

    const transformLoadedVirtual = await runTransform(plugin, compiled as string, virtualId!)
    expect(transformLoadedVirtual).toBeNull()
  })

  it('moves Vue novacss style blocks into inline nova-template virtual modules', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <template>
          <NovaCanvas>
            <TextBlock class="title" text="Demo" />
          </NovaCanvas>
        </template>

        <style lang="novacss" scoped>
        TextBlock.title { color: #111111; }
        </style>

        <style>
        .page { display: block; }
        </style>
      `,
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).not.toContain('lang="novacss"')
    expect(code).toContain('.page { display: block; }')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('styleSheet:props.styleSheet ?? styleSheet')
    expect(compiled).toContain('#111111')
  })

  it('registers unscoped Vue novacss style blocks globally', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <script setup lang="ts">
        const enabled = true
        </script>

        <template>
          <section v-if="enabled" />
        </template>

        <style lang="novacss">
        @theme light {
          TimelineChart {
            --nova-timeline-timescale-bg: #ffffff;
          }
        }
        </style>
      `,
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).not.toContain('lang="novacss"')
    expect(code).toContain('import { Nova as __NovaRuntime } from \'@endge/nova\'')
    expect(code).toContain('__NovaRuntime.import(__novaGlobalStyleSheet')
  })

  it('does not treat lang novascc as NovaCSS', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <template>
          <NovaCanvas>
            <Root class="screen" />
          </NovaCanvas>
        </template>

        <style lang="novascc">
        Root.screen { background: #ffffff; }
        </style>
      `,
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain('lang="novascc"')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).not.toContain('#ffffff')
  })

  it('transforms multiple NovaCanvas instances independently', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><section><NovaCanvas><TextBlock text="One" /></NovaCanvas><NovaCanvas><TextBlock text="Two" /></NovaCanvas></section></template>',
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    const virtualIds = [...code.matchAll(/from "(virtual:nova-template:[^"]+)"/g)].map(match => match[1])

    expect(code).toContain('import __NovaTemplate0')
    expect(code).toContain('import __NovaTemplate1')
    expect(virtualIds).toHaveLength(2)

    const first = await runLoad(plugin, virtualIds[0])
    const second = await runLoad(plugin, virtualIds[1])
    expect(first).toContain('One')
    expect(first).not.toContain('Two')
    expect(second).toContain('Two')
    expect(second).not.toContain('One')
  })

  it('normalizes for sources, simple event handlers and keeps loop locals intact', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<script setup lang="ts">const rows = []; const selected = true; function onSelect() {}</script><template><NovaCanvas><TextBlock for="row in rows" :key="row.id" if="selected" :text="row.title" @press="onSelect" /></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain(':rows="rows"')
    expect(code).toContain(':selected="selected"')
    expect(code).toContain(':nova-handler-on-select="onSelect"')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('__novaFor(props.rows).flatMap((row, index)')
    expect(compiled).toContain('row.title')
    expect(compiled).toContain('props.selected')
    expect(compiled).toContain('onPress:props.novaHandlerOnSelect')
  })

  it('normalizes bound control-flow sources in inline NovaCanvas DSL', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<script setup lang="ts">const rows = []; const selected = true</script><template><NovaCanvas><TextBlock :for="row in rows" :key="row.id" :if="selected" :text="row.title" /></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain(':rows="rows"')
    expect(code).toContain(':selected="selected"')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('__novaFor(props.rows).flatMap((row, index)')
    expect(compiled).toContain('(props.selected) ?')
    expect(compiled).toContain('row.title')
  })

  it('keeps legacy v-if/v-for unsupported in inline NovaCanvas DSL', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><TextBlock v-for="row in rows" :key="row.id" v-if="selected" :text="row.title" /></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )
    const code = (result as { code: string }).code
    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]

    expect(virtualId).toBeTruthy()
    await expect(runLoad(plugin, virtualId!)).rejects.toThrow(/unsupported-directive/)
  })

  it('keeps explicit top-level Root as the only Root wrapper', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><Root id="manual-root"><TextBlock text="Demo" /></Root></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect((compiled as string).match(/type:__NovaUIKit\.Root/g)).toHaveLength(1)
    expect(compiled).toContain('manual-root')
  })

  it('preserves #overlay as Vue slot while compiling default Nova DSL', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><TextBlock text="Demo" /><template #overlay><button>Update</button></template></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain('<template #overlay><button>Update</button></template>')
    expect(code).toContain('<nova-template :component="__NovaTemplate0"')
    expect(code).not.toContain('<TextBlock text="Demo" />')
  })

  it('compiles explicit #nova slot DSL and exposes canvas namespace', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<script setup lang="ts">const selected = true</script><template><NovaCanvas><template #nova="{ canvas }"><Root :width="canvas.width" :height="canvas.height"><TextBlock if="selected" text="Demo" /></Root></template><template #overlay><button>Update</button></template></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain(':selected="selected"')
    expect(code).toContain('<template #overlay><button>Update</button></template>')
    expect(code).toContain('<nova-template :component="__NovaTemplate0"')
    expect(code).not.toContain('#nova="{ canvas }"')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('const canvas = { width: this.width, height: this.height };')
    expect(compiled).toContain('width:canvas.width')
    expect(compiled).toContain('height:canvas.height')
    expect(compiled).toContain('props.selected')
  })

  it('compiles Component src through default-slot Nova DSL and forwards attrs to marker props', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><Component src="@/demo/Chart.nova" :options="options" @select="onSelect" /></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain(':options="options"')

    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('import __NovaComponent0 from "@/demo/Chart.nova"')
    expect(compiled).toContain('options:props.options')
    expect(code).toContain(':nova-handler-on-select="onSelect"')
    expect(compiled).toContain('events:{select:props.novaHandlerOnSelect}')
  })

  it('does not transform source #nova-template slots anymore', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><template #nova-template><Root /></template></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    expect(result).toBeNull()
  })

  it('does not transform legacy source nova-template tags anymore', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><NovaCanvas><nova-template><Root /></nova-template></NovaCanvas></template>',
      sourcePath('src/pages/Page.vue'),
    )

    expect(result).toBeNull()
  })

  it('extracts TimelineTaskProfile children from public Vue TimelineChart', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <script setup lang="ts">
        const data = []
        </script>

        <template>
          <TimelineChart :data="data" task-profile-by="status">
            <TimelineTaskProfile name="planned" v-slot="{ task, width, height }">
              <Rect :width="width" :height="height" background="#e8eef8" />
              <TextBlock :text="task.title" :width="width - 24" :height="height" />
            </TimelineTaskProfile>

            <TimelineTaskProfile name="active" v-slot="{ task, width, height }">
              <Rect :width="width" :height="height" background="#2563eb" />
              <TextBlock :text="task.title" :width="width - 24" :height="height" color="#ffffff" />
            </TimelineTaskProfile>
          </TimelineChart>
        </template>
      `,
      sourcePath('src/pages/Timeline.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain('const __timelineTaskProfiles0 = {defaultProfileId:\'default\',profiles:{')
    expect(code).toContain(':compiled-task-profiles="__timelineTaskProfiles0"')
    expect(code).not.toContain('<TimelineTaskProfile')
    expect(code).toContain('task-profile-by="status"')
    expect(code).toContain('schema:(__timelineTask) =>')
    expect(code).toContain("type:'rect'")
    expect(code).toContain("type:'text'")
  })

  it('extracts TimelineChart public Vue runtime children into compiled root children', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <script setup lang="ts">
        const data = []
        const options = {}
        </script>

        <template>
          <TimelineChart :data="data" :options="options">
            <Flex direction="column" :width="900" :height="360">
              <TimelineChart.TimeScale render-mode="overlay" :layout="{ height: 56 }">
                <template #overlay="{ majorTicks }">
                  <TextBlock for="tick in majorTicks" :key="tick.value" :text="tick.label" />
                </template>
              </TimelineChart.TimeScale>
              <TimelineChart.Grid render-mode="replace" :layout="{ flexGrow: 1 }" />
            </Flex>
          </TimelineChart>
        </template>
      `,
      sourcePath('src/pages/TimelinePublicChildren.vue'),
    )

    const code = (result as { code: string }).code
    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()
    expect(code).toContain(':compiled-root-children="[{ type: __TimelineRootChildren0 }]"')
    expect(code).not.toContain('<TimelineChart.TimeScale')

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('type:"TimelineChart.TimeScale"')
    expect(compiled).toContain('renderMode:"overlay"')
    expect(compiled).toContain('slots:{overlay:')
    expect(compiled).toContain('type:"TimelineChart.Grid"')
  })

  it('extracts TimelineChart public Vue group columns into compiled schema factories', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <script setup lang="ts">
        const data = []
        </script>

        <template>
          <TimelineChart :data="data">
            <TimelineChart.GroupPanel>
              <TimelineChart.GroupColumn id="status">
                <template #cell="{ group, x, y, width, height }">
                  <Circle :x="x + 8" :y="y + 8" :radius="4" :background="group.item.color" />
                </template>
              </TimelineChart.GroupColumn>
            </TimelineChart.GroupPanel>
          </TimelineChart>
        </template>
      `,
      sourcePath('src/pages/TimelineGroupColumns.vue'),
    )

    const code = (result as { code: string }).code
    expect(code).toContain('const __timelineGroupColumnTemplates0 = {')
    expect(code).toContain(':compiled-group-column-templates="__timelineGroupColumnTemplates0"')
    expect(code).toContain('status:{')
    expect(code).toContain("type:'circle'")
    expect(code).not.toContain('<TimelineChart.GroupPanel')
  })

  it('passes TimelineTaskProfile children to TimelineChart.Root inside NovaCanvas DSL', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <script setup lang="ts">
        const data = []
        </script>

        <template>
          <NovaCanvas>
            <TimelineChart.Root :data="data" task-profile-by="status">
              <TimelineTaskProfile name="planned" v-slot="{ task, width, height }">
                <Rect :width="width" :height="height" background="#e8eef8" />
                <TextBlock :text="task.title" :width="width - 24" :height="height" />
              </TimelineTaskProfile>
            </TimelineChart.Root>
          </NovaCanvas>
        </template>
      `,
      sourcePath('src/pages/TimelineRoot.vue'),
    )

    const code = (result as { code: string }).code
    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('taskProfiles:{defaultProfileId:\'default\',profiles:{')
    expect(compiled).toContain('planned:{')
    expect(compiled).toContain("type:'rect'")
    expect(compiled).toContain("type:'text'")
    expect(compiled).not.toContain('type:"TimelineTaskProfile"')
  })

  it('passes external TimelineChart.GroupPanel templates to TimelineChart.Root inside NovaCanvas DSL', async () => {
    const plugin = novaVitePlugin()
    const dir = createTempDir()
    const pageFile = path.join(dir, 'TimelineRootGroups.vue')
    const groupDir = path.join(dir, 'templates/groups')
    fs.mkdirSync(dir, { recursive: true })
    fs.mkdirSync(groupDir, { recursive: true })
    fs.writeFileSync(path.join(groupDir, 'GroupPanel.nova'), `
      <template>
        <TimelineChart.GroupPanel>
          <TimelineChart.GroupColumn id="status">
            <template #cell="{ group, x, y }">
              <Circle :x="x + 8" :y="y + 8" :radius="4" :background="group.item.color" />
            </template>
          </TimelineChart.GroupColumn>
        </TimelineChart.GroupPanel>
      </template>
    `)

    const result = await runTransform(
      plugin,
      `
        <template>
          <NovaCanvas>
            <TimelineChart.Root>
              <template src="./templates/groups/GroupPanel.nova" />
            </TimelineChart.Root>
          </NovaCanvas>
        </template>
      `,
      pageFile,
    )

    const code = (result as { code: string }).code
    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('compiledGroupColumnTemplates:{')
    expect(compiled).toContain('status:{')
    expect(compiled).toContain("type:'circle'")
    expect(compiled).not.toContain('type:"TimelineChart.GroupPanel"')
  })

  it('keeps TimelineChart.Root runtime children when extracting task profiles', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      `
        <script setup lang="ts">
        const data = []
        const options = {}
        const groupsOnLeft = true
        </script>

        <template>
          <NovaCanvas>
            <TimelineChart.Root sync="auto" :data="data" :options="options">
              <Flex direction="row" :width="1000" :height="520">
                <TimelineChart.GroupsPanel id="timeline-groups" :layout="{ width: 220, order: groupsOnLeft ? 0 : 1 }" />
                <Flex direction="column" :layout="{ flexGrow: 1, order: groupsOnLeft ? 1 : 0 }">
                  <TimelineChart.TimeScale id="timeline-scale" :layout="{ height: 52 }" />
                  <TimelineChart.TasksPanel id="timeline-tasks" :layout="{ flexGrow: 1 }" />
                </Flex>
              </Flex>

              <TimelineTaskProfile name="planned" v-slot="{ task, width, height }">
                <Rect :width="width" :height="height" background="#e8eef8" />
                <TextBlock :text="task.title" :width="width - 24" :height="height" />
              </TimelineTaskProfile>
            </TimelineChart.Root>
          </NovaCanvas>
        </template>
      `,
      sourcePath('src/pages/TimelineParts.vue'),
    )

    const code = (result as { code: string }).code
    const virtualId = code.match(/from "(virtual:nova-template:[^"]+)"/)?.[1]
    expect(virtualId).toBeTruthy()

    const compiled = await runLoad(plugin, virtualId!)
    expect(compiled).toContain('taskProfiles:{defaultProfileId:\'default\',profiles:{')
    expect(compiled).toContain('children:[{type:__NovaUIKit.Flex')
    expect(compiled).toContain('type:"TimelineChart.GroupsPanel"')
    expect(compiled).toContain('type:"TimelineChart.TimeScale"')
    expect(compiled).toContain('type:"TimelineChart.TasksPanel"')
    expect(compiled).not.toContain('type:"TimelineTaskProfile"')
  })

  it('does not parse ordinary Vue templates without NovaCanvas', async () => {
    const plugin = novaVitePlugin()

    const result = await runTransform(
      plugin,
      '<template><section><input></section></template>',
      sourcePath('src/pages/Plain.vue'),
    )

    expect(result).toBeNull()
  })
})

async function runTransform(plugin: Plugin, source: string, id: string): Promise<unknown> {
  const transform = plugin.transform
  const context = {
    /**
     * Выполняет действие addWatchFile в рамках ответственности текущего класса.
     */
    addWatchFile() {},
  }

  if (typeof transform === 'function') {
    return await transform.call(context as never, source, id)
  }

  return await transform?.handler.call(context as never, source, id)
}

async function runLoad(plugin: Plugin, id: string): Promise<unknown> {
  const load = plugin.load
  const context = {
    /**
     * Выполняет действие addWatchFile в рамках ответственности текущего класса.
     */
    addWatchFile() {},
  }

  if (typeof load === 'function') {
    return await load.call(context as never, id)
  }

  return await load?.handler.call(context as never, id)
}

function createTempDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nova-compiler-'))
  fs.rmSync(dir, { recursive: true, force: true })
  TEMP_DIRS.push(dir)
  return dir
}

function sourcePath(relativePath: string): string {
  return path.join(process.cwd(), relativePath)
}
